
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thinkpad
 */
public class Ejecutar extends javax.swing.JFrame {

    /**
     * Creates new form Ejecutar
     */
    public Ejecutar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Ventana aplicacion = new Ventana();
		aplicacion.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); /*Al presionar X, cierra la ventana y el programa.*/
		//aplicacion.pack();/*redimensiona autom�ticamente el tama�o de la ventana al espacio ocupado por los botones.*/
		aplicacion.setVisible(true);/*Hace visible el Frame o la ventana.*/
		aplicacion.setLocationRelativeTo(null);/*Coloca la ventana al centro del monitor*/
		aplicacion.setResizable(false);
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
